vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

require "john.options"
require "john.keymaps"
require "john.plugins"
require "john.colorscheme"
require "john.cmp"
require "john.lsp.mason"
require "john.telescope"
require "john.treesitter"
require "john.autopairs"
require "john.comment"
require "john.gitsigns"
require "john.toggleterm"
require "john.icons"
require "john.nvimtree"
require "john.lsp.nullls"
require "john.indent_blankline"
require "john.lualine"
